# Core data science and numerical computing
numpy==2.1.2
pandas==2.3.0
scipy==1.15.3
scikit-learn==1.7.0
scikit-image==0.25.2
matplotlib==3.10.3

# Deep learning frameworks
torch==2.7.1+cu126
torchvision==0.22.1+cu126
torchaudio==2.7.1+cu126
torchmetrics==1.7.3
pytorch-lightning==2.5.1

# HuggingFace & transformers
transformers==4.52.4
tokenizers==0.21.2
huggingface-hub==0.33.0
safetensors==0.5.3

# Vision & image processing
opencv-python-headless==4.11.0.86
imageio==2.37.0
albumentations==2.0.8
albucore==0.0.24
timm==1.0.15
Pillow==11.0.0

# NLP & text processing
nltk==3.9.1
antlr4-python3-runtime==4.9.3
sentencepiece
regex==2024.11.6
rouge-score==0.1.2

# HTTP & networking
aiohttp==3.12.13
aiosignal==1.3.2
aiohappyeyeballs==2.6.1
async-timeout==5.0.1
grpcio==1.73.1
requests==2.32.4
urllib3==2.5.0
idna==3.10
charset-normalizer==3.4.2

# Utilities & configuration
pyyaml==6.0.2
omegaconf==2.3.0
absl-py==2.3.0
click==8.2.1
tqdm==4.67.1
packaging==25.0
psutil==7.0.0
filelock==3.13.1
lazy-loader==0.4
markupsafe==2.1.5
jinja2==3.1.4
pydantic==2.11.7
pydantic-core==2.33.2
protobuf==6.31.1
python-dateutil==2.9.0.post0
pytz==2025.2
tzdata==2025.2

# Logging & visualization
tensorboard==2.19.0
tensorboard-data-server==0.7.2
wandb==0.20.1
coloredlogs==15.0.1
humanfriendly==10.0

# Evaluation metrics
pycocoevalcap==1.2
pycocotools==2.0.10

# Computer vision models
segmentation-models-pytorch==0.5.0

# Additional packages
hf-xet==1.1.5
propcache==0.3.2
stringzilla==3.12.5
simsimd==6.4.9
gitdb==4.0.12
GitPython==3.1.44
blinker==1.9.0
contourpy==1.3.2
cycler==0.12.1
fonttools==4.58.4
kiwisolver==1.4.8
mpmath==1.3.0
networkx==3.3
pyparsing==3.2.3
sympy==1.13.3
lightning-utilities==0.14.3
markdown==3.8.2
msgspec==0.19.0
multidict==6.6.2
netron==7.6.5
netron-export==0.2.5
ninja==1.12.1
onnx==1.18.0
onnxruntime==1.22.1
pydicom==3.0.1
pydot==4.0.1
pyee==9.0.4
sentry-sdk==2.32.0
setproctitle==1.3.6
setuptools==70.2.0
smmap==5.0.2
tifffile==2025.5.10
triton==3.3.1
typing-extensions==4.12.2
typing-inspection==0.4.1
werkzeug==3.1.3
yarl==1.20.1
greenlet==2.0.2
flatbuffers==25.2.10
cachelib==0.13.0
frozenlist==1.7.0
fsspec==2024.6.1
playwright==1.37.0
annotated-types==0.7.0
itsdangerous==2.2.0
flask==2.3.2
flask-cors==6.0.1
flask-session==0.8.0
