name: pytorch_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=2.3.0
  - pandas=2.3.0
  - matplotlib=3.10.3
  - scikit-learn=1.7.0
  - scipy=1.15.3
  - seaborn
  - absl-py=2.3.0
  - aiohttp=3.12.13
  - aiosignal=1.3.2
  - albumentations=2.0.8
  - antlr4-python3-runtime=4.9.3
  - attrs=25.3.0
  - certifi=2025.6.15
  - charset-normalizer=3.4.2
  - click=8.2.1
  - contourpy=1.3.2
  - cycler=0.12.1
  - filelock=3.18.0
  - fonttools=4.58.4
  - fsspec=2025.5.1
  - gitpython=3.1.44
  - imageio=2.37.0
  - jinja2=3.1.6
  - joblib=1.5.1
  - kiwisolver=1.4.8
  - lazy-loader=0.4
  - lightning-utilities=0.14.3
  - markdown=3.8.2
  - markupsafe=3.0.2
  - mpmath=1.3.0
  - networkx=3.5
  - nltk=3.9.1
  - omegaconf=2.3.0
  - packaging=25.0
  - pillow=11.2.1
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydicom=3.0.1
  - pyparsing=3.2.3
  - python-dateutil=2.9.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - regex=2024.11.6
  - safetensors=0.5.3
  - scikit-image=0.25.2
  - sentry-sdk=2.30.0
  - setproctitle=1.3.6
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - stringzilla=3.12.5
  - sympy=1.14.0
  - tensorboard=2.19.0
  - threadpoolctl=3.6.0
  - tifffile=2025.6.11
  - timm=1.0.15
  - tokenizers=0.21.1
  - torchmetrics=1.7.3
  - tqdm=4.67.1
  - typing-extensions=4.14.0
  - typing-inspection=0.4.1
  - wandb=0.20.1
  - werkzeug=3.1.3
  - yarl=1.20.1

  - pip:
    - torch==2.7.1
    - torchvision==0.22.1
    - transformers==4.52.4
    - huggingface-hub==0.33.0
    - grpcio==1.73.0
    - opencv-python==4.11.0.86
    - opencv-python-headless==4.11.0.86
    - frozenlist==1.7.0
    - tensorboard-data-server==0.7.2
    - propcache==0.3.2
    - protobuf==6.31.1
    - albucore==0.0.24
    - hf-xet==1.1.4
    - segmentation-models-pytorch==0.5.0
    - tzdata==2025.2
