name: pytorch_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  # Core data science
  - numpy=2.3.0
  - pandas=2.3.0
  - scipy=1.15.3
  - scikit-learn=1.7.0
  - scikit-image=0.25.2
  - matplotlib=3.10.3

  # Deep learning frameworks
  - pytorch=2.7.1       # CUDA-compatible build from conda-forge
  - torchvision=0.22.1
  - torchaudio=2.7.1    # match torch version
  - torchmetrics=1.7.3
  - pytorch-lightning=2.5.1  # .post0 is fine via pip

  # HuggingFace & transformers
  - transformers=4.52.4
  - tokenizers=0.21.1
  - huggingface-hub=0.33.0
  - safetensors=0.5.3

  # Vision & image
  - opencv=4.11.0        # includes headless
  - imageio=2.37.0
  - albumentations=2.0.8
  - timm=1.0.15

  # NLP & tokenization
  - nltk=3.9.1
  - antlr4-python3-runtime=4.9.3
  - sentencepiece

  # HTTP & async
  - aiohttp=3.12.13
  - aiosignal=1.3.2
  - grpcio=1.73.0

  # Utilities
  - pyyaml=6.0.2
  - omegaconf=2.3.0
  - absl-py=2.3.0
  - click=8.2.1
  - tqdm=4.67.1
  - pillow=11.2.1
  - packaging=25.0
  - psutil=7.0.0
  - filelock=3.18.0
  - lazy-loader=0.4
  - markupsafe=3.0.2
  - jinja2=3.1.6
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - protobuf=6.31.1

  # Logging & visualization
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.2
  - wandb=0.20.1

  # JSON, parsing, etc.
  - regex=2024.11.6
  - jsonschema
  - python-dateutil=2.9.0
  - pytz=2025.2

  # Evaluation metrics
  - rouge_score=0.1.2
  - pycocoevalcap=1.2
  - pycocotools=2.0.10

  # Additional
  - segmentation-models-pytorch=0.5.0

  # Install specific pip-only packages
  - pip:
    - hf-xet==1.1.4
    - propcache==0.3.2
    - tzdata==2025.2
    - stringzilla==3.12.5
    - simsimd==6.4.9
    - gitdb==4.0.12
    - GitPython==3.1.44
